apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmops-deployment
  labels:
    app: llmops
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: llmops
  template:
    metadata:
      labels:
        app: llmops
    spec:
      containers:
      - name: llmops-container
        image: morlom/llmops:latest 
        ports:
        - containerPort: 5000 # Matches the EXPOSE instruction in Dockerfile
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OPENAI_API_KEY
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SECRET_KEY